package de.bund.bsi.tr_esor.checktool.validation.signatures;

/**
 * This is a non-exhaustive collection of ResultMessages generated by the eCard-Service that require special handling.
 *
 * @author ETR
 */
final class ECardResultMessage
{

    public static final String RESULTMESSAGE_NO_PLUGIN = "No Plugin found!";

    public static final String RESULTMESSAGE_FORMAT_NOT_RECOGNIZED = "Signature format not recognized";
}
